# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-29 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingbookingapplication', '0002_auto_20190929_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staffmail',
            field=models.EmailField(max_length=50),
        ),
    ]
